### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by javiramos1** [gustavonalle/oc-cluster-up#5]
Does this works on Ubuntu?

I'm getting this error:

[openshift/dind] Step 8/17 : RUN dnf -y update && dnf -y install docker glibc-langpack-en iptables openssh-clients openssh-server tcpdump
[openshift/dind]  ---> Running in a43e799706b8
[openshift/dind] Error: Failed to synchronize cache for repo 'updates'
[openshift/dind] The command '/bin/sh -c dnf -y update && dnf -y install docker glibc-langpack-en iptables openssh-clients openssh-server tcpdump' returned a non-zero code: 1
[ERROR] hack/dind-cluster.sh:800: `return "${result}"` exited with status 1.
/root//go/src/github.com/openshift/origin/run.sh: line 6: /root/go/src/github.com/openshift/origin/dind-openshift.rc: No such file or directory

....

Error: No such object: openshift-master
2019/01/15 14:12:27 cmd/main: cookies are not secure because base-address is not https!
2019/01/15 14:12:27 cmd/main: Error initializing OIDC authenticator: file examples/ca.crt contained no CA data

Thank you

**Comment by gustavonalle** [comment]
Should work on Ubuntu. It seems a network issue happened during the initial build of the images. If you retry, do you get the same error?

**Comment by javiramos1** [comment]
I tried the network at work and home and same issue :(

**Comment by javiramos1** [comment]
This is my docker info.:

Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 38
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.0-041900-generic
Operating System: Ubuntu 18.10
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 31.27GiB
Name: javier-Recoil-II
ID: ON3M:GIDT:XQ6K:3KEA:BDIL:V2T4:2KM2:4NRW:PYRM:VSPF:IM2A:GBHJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support




Let me try your test... thanks!

**Comment by gustavonalle** [comment]
It seems Ubuntu has DNS issues with docker. So one workaround would be to add 8.8.8.8 to the /etc/docker/daemon.json file:

{
    "dns": ["existent address", "8.8.8.8"]
} 

and restart docker.

**Comment by gustavonalle** [comment]
I've just tested with ```Ubuntu 18.04.1 LTS```, docker version ```18.06.1-ce, build e68fc7a``` and both the oc-cluster-up and the test above works without changing any DNS.  

Apparently Docker-CE can handle correctly the fact that ubuntu uses ```dnsmaq```, where ```/etc/resolv.conf``` has only a local DNS and the real nameserver is located in ```/run/systemd/resolve/resolv.conf```.

Please make sure to use the docker version above and open a new issue if the problem persists.
